"""Pavelo Agent Service — AI orchestration with LangGraph (S5-04, S5-06, S6-03)."""

from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from contextlib import asynccontextmanager
from pydantic import BaseModel
from typing import Optional
import json
import uuid
import asyncio

import structlog
from langchain_core.messages import HumanMessage

from src.config import settings
from src.graph import agent_graph
from src.state import AgentState
from src.nodes.response_generator import response_generator_stream, _build_visual_payloads

logger = structlog.get_logger()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan — startup and shutdown."""
    logger.info("agent_service_starting", port=settings.port)
    yield
    logger.info("agent_service_stopping")


app = FastAPI(
    title="Pavelo Agent Service",
    version="0.3.0",
    description="AI Agent orchestration service for Pavelo/Xara (chat + voice)",
    lifespan=lifespan,
)

# Track active voice pipelines
_active_pipelines: dict[str, "VoicePipeline"] = {}


# --- Request / Response Models ---

class ChatRequest(BaseModel):
    """Chat request from the API gateway."""
    user_id: str
    conversation_id: str
    message: str
    stream: bool = True
    persona_name: Optional[str] = None
    persona_tone: Optional[str] = None


class ChatResponse(BaseModel):
    """Non-streaming chat response."""
    response: str
    intent: str
    visual_payloads: list = []
    conversation_id: str


# --- Endpoints ---

@app.get("/health")
async def health():
    """Health check endpoint."""
    return {
        "status": "ok",
        "service": "agent",
        "version": "0.3.0",
        "active_voice_sessions": len(_active_pipelines),
    }


@app.post("/api/v1/chat")
async def chat(request: ChatRequest):
    """Process a chat message through the LangGraph agent.

    Supports both streaming (SSE) and non-streaming responses.

    The agent pipeline:
    1. Memory retrieval (Mem0 episodic memory)
    2. Intent classification (OpenAI)
    3. Tool execution (search, details, comparison, mortgage)
    4. Response generation (OpenAI with full context)
    5. Memory write (persist new facts to Mem0)
    """
    logger.info(
        "chat_request",
        user_id=request.user_id,
        conversation_id=request.conversation_id,
        message_preview=request.message[:100],
        stream=request.stream,
    )

    # Build initial state
    initial_state = AgentState(
        user_id=request.user_id,
        session_id=request.conversation_id,
        messages=[HumanMessage(content=request.message)],
    )

    config = {"configurable": {"thread_id": request.conversation_id}}

    if request.stream:
        return StreamingResponse(
            _stream_response(initial_state, config, request),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
                "X-Accel-Buffering": "no",
            },
        )

    # Non-streaming response
    try:
        result = await agent_graph.ainvoke(initial_state, config=config)

        # Extract response from the last AI message
        response_text = ""
        if result.messages:
            last_msg = result.messages[-1]
            if hasattr(last_msg, "content"):
                response_text = last_msg.content

        visual_payloads = getattr(result, "visual_payloads", [])

        return ChatResponse(
            response=response_text,
            intent=result.intent,
            visual_payloads=visual_payloads,
            conversation_id=request.conversation_id,
        )

    except Exception as e:
        logger.error("chat_error", error=str(e))
        raise HTTPException(status_code=500, detail=f"Agent error: {str(e)}")


async def _stream_response(state: AgentState, config: dict, request: ChatRequest):
    """SSE streaming generator with real token-by-token streaming.

    Uses LangGraph's astream_events to execute the graph and stream
    response tokens as they are generated by the LLM.

    Yields SSE events:
      data: {"type": "token", "content": "..."}
      data: {"type": "visual_payload", "payload": {...}}
      data: {"type": "done"}
      data: [DONE]
    """
    try:
        streamed_any_token = False
        visual_payloads_sent = False

        async for event in agent_graph.astream_events(state, config=config, version="v2"):
            kind = event.get("event", "")
            name = event.get("name", "")

            # Intercept chat model streaming tokens from the response generator
            if kind == "on_chat_model_stream" and "response_generator" in (event.get("tags") or [name]):
                chunk = event.get("data", {}).get("chunk")
                if chunk and hasattr(chunk, "content") and chunk.content:
                    streamed_any_token = True
                    yield f"data: {json.dumps({'type': 'token', 'content': chunk.content})}\n\n"

            # Capture visual payloads when response_generator node completes
            if kind == "on_chain_end" and name == "response_generator" and not visual_payloads_sent:
                output = event.get("data", {}).get("output", {})
                visual_payloads = output.get("visual_payloads", [])
                for vp in visual_payloads:
                    yield f"data: {json.dumps({'type': 'visual_payload', 'payload': vp})}\n\n"
                visual_payloads_sent = True

        # If no tokens were streamed (e.g. no OpenAI key, stub response),
        # fall back to extracting the final response from a full invoke
        if not streamed_any_token:
            result = await agent_graph.ainvoke(state, config=config)
            response_text = ""
            if result.get("messages"):
                last_msg = result["messages"][-1]
                if hasattr(last_msg, "content"):
                    response_text = last_msg.content

            if response_text:
                yield f"data: {json.dumps({'type': 'token', 'content': response_text})}\n\n"

            # Send visual payloads from fallback
            if not visual_payloads_sent:
                for vp in result.get("visual_payloads", []):
                    yield f"data: {json.dumps({'type': 'visual_payload', 'payload': vp})}\n\n"

        yield f"data: {json.dumps({'type': 'done'})}\n\n"
        yield "data: [DONE]\n\n"

    except Exception as e:
        logger.error("stream_error", error=str(e))
        yield f"data: {json.dumps({'type': 'error', 'content': str(e)})}\n\n"
        yield "data: [DONE]\n\n"


@app.post("/api/v1/chat/stream")
async def chat_stream(request: ChatRequest):
    """Explicit streaming endpoint (SSE).

    Alternative to the main /api/v1/chat endpoint with stream=true.
    """
    request.stream = True
    return await chat(request)


# --- Voice Pipeline Endpoints (S6-03) ---

class VoiceSessionRequest(BaseModel):
    """Request to start a voice pipeline for a room."""
    room_name: str
    user_id: str
    conversation_id: str
    session_id: Optional[str] = None
    language: str = "en"


class VoiceSessionResponse(BaseModel):
    """Response after starting/stopping a voice pipeline."""
    status: str
    room_name: str
    message: str


@app.post("/api/v1/voice/start")
async def start_voice_pipeline(request: VoiceSessionRequest):
    """Start a voice pipeline for a LiveKit room.

    Called by the API gateway after creating a voice session.
    The pipeline joins the LiveKit room as the agent participant.
    """
    if request.room_name in _active_pipelines:
        return VoiceSessionResponse(
            status="already_running",
            room_name=request.room_name,
            message="Pipeline already running for this room",
        )

    try:
        from src.voice.pipeline import VoicePipeline

        pipeline = VoicePipeline(
            room_name=request.room_name,
            user_id=request.user_id,
            conversation_id=request.conversation_id,
            language=request.language,
            session_id=request.session_id,
        )

        _active_pipelines[request.room_name] = pipeline

        # Start pipeline in background
        asyncio.create_task(_run_pipeline(request.room_name, pipeline))

        logger.info(
            "voice_pipeline_started",
            room=request.room_name,
            user_id=request.user_id,
        )

        return VoiceSessionResponse(
            status="started",
            room_name=request.room_name,
            message="Voice pipeline started",
        )

    except Exception as e:
        logger.error("voice_pipeline_start_error", error=str(e))
        raise HTTPException(status_code=500, detail=f"Failed to start pipeline: {str(e)}")


async def _run_pipeline(room_name: str, pipeline):
    """Run voice pipeline in background and clean up on completion."""
    try:
        await pipeline.start()
    except Exception as e:
        logger.error("voice_pipeline_runtime_error", room=room_name, error=str(e))
    finally:
        _active_pipelines.pop(room_name, None)
        logger.info("voice_pipeline_cleaned_up", room=room_name)


@app.post("/api/v1/voice/stop")
async def stop_voice_pipeline(request: VoiceSessionRequest):
    """Stop a voice pipeline for a LiveKit room."""
    pipeline = _active_pipelines.get(request.room_name)

    if not pipeline:
        return VoiceSessionResponse(
            status="not_found",
            room_name=request.room_name,
            message="No active pipeline for this room",
        )

    try:
        await pipeline.stop()
        _active_pipelines.pop(request.room_name, None)

        return VoiceSessionResponse(
            status="stopped",
            room_name=request.room_name,
            message="Voice pipeline stopped",
        )
    except Exception as e:
        logger.error("voice_pipeline_stop_error", error=str(e))
        raise HTTPException(status_code=500, detail=f"Failed to stop pipeline: {str(e)}")


@app.get("/api/v1/voice/status/{room_name}")
async def get_voice_status(room_name: str):
    """Get the status of a voice pipeline."""
    pipeline = _active_pipelines.get(room_name)

    if not pipeline:
        return {"status": "inactive", "room_name": room_name}

    return {
        "status": "active",
        "room_name": room_name,
        "metrics": pipeline.metrics,
    }


# --- Memory Consolidation Endpoints (S8-01) ---

class ConsolidateRequest(BaseModel):
    """Optional body for consolidation request."""
    force: bool = False


@app.post("/api/v1/memory/consolidate/{user_id}")
async def consolidate_memory(user_id: str, request: Optional[ConsolidateRequest] = None):
    """Consolidate cross-session memories for a user.
    
    Extracts facts from all conversations, deduplicates,
    and updates the user's consolidated profile.
    """
    from src.memory.consolidation import consolidate_user_memory
    
    logger.info("memory_consolidation_requested", user_id=user_id)
    
    try:
        result = await consolidate_user_memory(user_id)
        return result
    except Exception as e:
        logger.error("memory_consolidation_error", user_id=user_id, error=str(e))
        raise HTTPException(status_code=500, detail=f"Consolidation failed: {str(e)}")


# --- Valuation Endpoint (S8-04) ---

class ValuationRequest(BaseModel):
    """Request for AI property valuation."""
    user_id: str
    address: str
    postcode: str
    property_type: str
    bedrooms: int
    bathrooms: int
    square_feet: Optional[int] = None
    year_built: Optional[int] = None
    features: list[str] = []


@app.post("/api/v1/valuation/generate")
async def generate_valuation(request: ValuationRequest):
    """Generate an AI-powered property valuation.
    
    Uses comparable search, price/sqft analysis, and market trends.
    """
    from src.tools.generate_valuation import generate_valuation_impl
    
    logger.info(
        "valuation_requested",
        user_id=request.user_id,
        postcode=request.postcode,
    )
    
    try:
        result = await generate_valuation_impl(
            address=request.address,
            postcode=request.postcode,
            property_type=request.property_type,
            bedrooms=request.bedrooms,
            bathrooms=request.bathrooms,
            square_feet=request.square_feet,
            year_built=request.year_built,
            features=request.features,
        )
        return result
    except Exception as e:
        logger.error("valuation_error", error=str(e))
        raise HTTPException(status_code=500, detail=f"Valuation failed: {str(e)}")


# --- Description Generation Endpoint (S8-03) ---

class DescriptionRequest(BaseModel):
    """Request for AI property description generation."""
    property_type: str
    bedrooms: int
    bathrooms: int
    square_feet: Optional[int] = None
    year_built: Optional[int] = None
    features: list[str] = []
    address: str = ""
    postcode: str = ""


@app.post("/api/v1/property/generate-description")
async def generate_description(request: DescriptionRequest):
    """Generate an AI property description from attributes."""
    from src.tools.generate_description import generate_description_impl
    
    try:
        result = await generate_description_impl(
            property_type=request.property_type,
            bedrooms=request.bedrooms,
            bathrooms=request.bathrooms,
            square_feet=request.square_feet,
            year_built=request.year_built,
            features=request.features,
            address=request.address,
            postcode=request.postcode,
        )
        return result
    except Exception as e:
        logger.error("description_gen_error", error=str(e))
        raise HTTPException(status_code=500, detail=f"Description generation failed: {str(e)}")
